-- Búsqueda controlada para el asistente de IA del Registro Civil.
-- La IA nunca recibe acceso SQL: solo puede usar estos filtros tipados.

create table if not exists public.rc_ai_consultas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  filtros jsonb not null default '{}'::jsonb,
  total integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.rc_ai_consultas enable row level security;

drop policy if exists rc_ai_consultas_insert_own on public.rc_ai_consultas;
create policy rc_ai_consultas_insert_own on public.rc_ai_consultas
for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists rc_ai_consultas_select_own on public.rc_ai_consultas;
create policy rc_ai_consultas_select_own on public.rc_ai_consultas
for select to authenticated
using (user_id = auth.uid());

revoke all on table public.rc_ai_consultas from public, anon;
grant select, insert on table public.rc_ai_consultas to authenticated;
grant all on table public.rc_ai_consultas to service_role;
grant usage, select on sequence public.rc_ai_consultas_id_seq to authenticated, service_role;

create index if not exists rc_ai_consultas_user_fecha_idx
on public.rc_ai_consultas(user_id, created_at desc);

create index if not exists rc_tramites_tipo_ano_idx
on public.rc_tramites(tipo, ano);

create index if not exists rc_tramites_fecha_idx
on public.rc_tramites(fecha);

create index if not exists rc_tramites_cedula_idx
on public.rc_tramites(cedula_titular);

create index if not exists rc_tramites_numero_idx
on public.rc_tramites(numero_acta, ano);

create or replace function public.rc_ai_buscar(
  p_tipo text default null,
  p_desde date default null,
  p_hasta date default null,
  p_ano integer default null,
  p_titular text default null,
  p_cedula text default null,
  p_numero_acta text default null,
  p_funcionario text default null,
  p_origen text default null,
  p_texto text default null,
  p_limite integer default 20
)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
  with parametros as (
    select
      nullif(btrim(p_tipo), '') tipo,
      p_desde desde,
      p_hasta hasta,
      p_ano ano,
      nullif(btrim(p_titular), '') titular,
      nullif(regexp_replace(p_cedula, '[^0-9]', '', 'g'), '') cedula,
      nullif(btrim(p_numero_acta), '') numero_acta,
      nullif(btrim(p_funcionario), '') funcionario,
      case when p_origen in ('archivo', 'sistema') then p_origen end origen,
      nullif(btrim(p_texto), '') texto,
      greatest(1, least(coalesce(p_limite, 20), 25)) limite
  ),
  filtrados as materialized (
    select t.id, t.tipo, t.titular, t.cedula_titular, t.numero_acta, t.ano,
           t.fecha, t.legacy, t.owner_usuario, t.estado, t.created_at, t.datos,
           d.datos as detalle_historico
    from public.rc_tramites t
    left join public.rc_tramites_detalle_links l on l.legacy_source_id = t.legacy_source_id
    left join public.rc_detalles_historicos d on d.act_key = l.act_key
    cross join parametros p
    where (p.tipo is null or t.tipo = p.tipo)
      and (p.desde is null or t.fecha >= p.desde)
      and (p.hasta is null or t.fecha <= p.hasta)
      and (p.ano is null or t.ano = p.ano)
      and (p.titular is null or t.titular ilike '%' || p.titular || '%')
      and (p.cedula is null or regexp_replace(coalesce(t.cedula_titular, ''), '[^0-9]', '', 'g') like '%' || p.cedula || '%'
           or regexp_replace(coalesce(t.datos::text, ''), '[^0-9]', '', 'g') like '%' || p.cedula || '%'
           or regexp_replace(coalesce(d.datos::text, ''), '[^0-9]', '', 'g') like '%' || p.cedula || '%')
      and (p.numero_acta is null or t.numero_acta = p.numero_acta)
      and (p.funcionario is null or t.owner_usuario ilike '%' || p.funcionario || '%')
      and (p.origen is null or (p.origen = 'archivo' and t.legacy is true)
           or (p.origen = 'sistema' and t.legacy is false))
      and (p.texto is null or concat_ws(' ', t.tipo, t.titular, t.cedula_titular,
            t.numero_acta, t.ano::text, t.owner_usuario, t.estado, t.datos::text, d.datos::text)
            ilike '%' || p.texto || '%')
  )
  select jsonb_build_object(
    'total', (select count(*) from filtrados),
    'fecha_min', (select min(fecha) from filtrados),
    'fecha_max', (select max(fecha) from filtrados),
    'por_tipo', coalesce((
      select jsonb_object_agg(tipo, cantidad)
      from (select tipo, count(*) cantidad from filtrados group by tipo order by count(*) desc) x
    ), '{}'::jsonb),
    'por_ano', coalesce((
      select jsonb_object_agg(ano::text, cantidad)
      from (select ano, count(*) cantidad from filtrados where ano is not null group by ano order by ano) x
    ), '{}'::jsonb),
    'por_funcionario', coalesce((
      select jsonb_object_agg(funcionario, cantidad)
      from (
        select coalesce(nullif(owner_usuario, ''), 'Sin funcionario') funcionario, count(*) cantidad
        from filtrados group by 1 order by count(*) desc limit 20
      ) x
    ), '{}'::jsonb),
    'resultados', coalesce((
      select jsonb_agg(to_jsonb(x))
      from (
        select id, tipo, titular, cedula_titular, numero_acta, ano, fecha,
               legacy, owner_usuario, estado, datos, detalle_historico
        from filtrados
        order by fecha desc nulls last, created_at desc
        limit (select limite from parametros)
      ) x
    ), '[]'::jsonb)
  );
$$;

revoke all on function public.rc_ai_buscar(text, date, date, integer, text, text, text, text, text, text, integer)
from public, anon;

grant execute on function public.rc_ai_buscar(text, date, date, integer, text, text, text, text, text, text, integer)
to authenticated, service_role;

notify pgrst, 'reload schema';
